CREATE TYPE unit_types as ENUM ('tbs', 'tsp', 'cup', 'cups', 'quarts', 'lbs', 'lb', 'oz', 'quart', 'ml', 'gram', 'grams');

CREATE TABLE ingredients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    food_item TEXT NOT NULL,
    amount INTEGER,
    recipe_id INTEGER
        REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,
    unit unit_types
);