CREATE TABLE ingredients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    food_item TEXT NOT NULL,
    amount INTEGER,
    measurement_id INTEGER
        REFERENCES measurements(id) ON DELETE CASCADE NOT NULL,
    recipe_id INTEGER
        REFERENCES recipes(id) ON DELETE CASCADE NOT NULL
);